Skip host details for archived scans and handle 500 error
JupiterOne/graph-tenable-cloud pull request #54
Opened 2021-05-04 17:20 UTC by kenanwarren

2021-05-04 17:29 UTC, aiwilliams requested changes

2021-05-04 17:29 UTC, aiwilliams commented on src/tenable/TenableClient.ts
> +        this.logger.info(
In this case, I think a `logger.warn` is appropriate.

An `info` for `404` is good because (presumably) we consider that to be an acceptable, expected type of response. The `500` is one we also expect to happen occasionally but is more than `info` because there may be data that we did not ingest, and it's easy to find in logs with `level=40` filter. An `error` level is appropriate if we expect the operator to know and act, and we would expect there to have been a corresponding event in Sentry.

2021-05-04 17:29 UTC, aiwilliams commented on src/tenable/TenableClient.ts
> +      } else if (err.statusCode === 500) {
Taking a look at [`makeRequest`](https://github.com/JupiterOne/graph-tenable-cloud/blob/dde27a2819a5cbe01a672ca4c06a973fe23070c9/src/tenable/TenableClient.ts#L243), it seems we are retrying `500` requests a few times. 👍

2021-05-04 18:21 UTC, kenanwarren commented on src/tenable/TenableClient.test.ts
> -  test("fetchScanDetail 500 error", async () => {
Removed this since we're logging the error now.

2021-05-04 18:46 UTC, kenanwarren commented on src/executionHandler.ts
> +        if (scanDetail.hosts && !scanDetail.info.is_archived) {
@aiwilliams This won't trigger the delete operations will it?

2021-05-04 18:52 UTC, aiwilliams commented on src/executionHandler.ts
> +        if (scanDetail.hosts && !scanDetail.info.is_archived) {
The [`persister.processEntities` for scans](https://github.com/JupiterOne/graph-tenable-cloud/blob/dde27a2819a5cbe01a672ca4c06a973fe23070c9/src/executionHandler.ts#L158) will take the old and the new resources to produce create, update, and delete operations. If the complete set cannot be loaded from the provider, it will delete things in the old set that are not represented in the new set.

2021-05-04 19:07 UTC, kenanwarren commented on src/executionHandler.ts
> +        if (scanDetail.hosts && !scanDetail.info.is_archived) {
With this change though the [processEntities](https://github.com/JupiterOne/graph-tenable-cloud/blob/dde27a2819a5cbe01a672ca4c06a973fe23070c9/src/executionHandler.ts#L295) won't be called for host vulnerabilities so the old ones should be persisted. Given that, I think we're good until we can get the export api changes in.

2021-05-05 15:50 UTC, aiwilliams approved these changes

2021-05-05 15:50 UTC, aiwilliams commented on src/executionHandler.ts
> +        if (scanDetail.hosts && !scanDetail.info.is_archived) {
Oh, right, sorry!

2021-05-05 17:09 UTC, merged